### ISSUE TITLE
Not able to download the pretrained models from the given path

### ISSUE THREAD

**Issue by varsha-devi** [danieljf24/hybrid_space#2]
Thanks for sharing your work. I am trying to reproduce your results; but I am not able to download your pretrained model using 

wget -P $MODELDIR http://8.210.46.84:8787/checkpoints/msrvtt10k_model_best.pth.tar

the web page is not responding. Kindly help me in resolving this issue.

**Comment by danieljf24** [comment]
Fixed. If you have any other questions, please feel free to contact us.

**Comment by RajArPatra** [comment]
Still not able to download
wget -P $MODELDIR http://8.210.46.84:8787/checkpoints/msrvtt10k_model_best.pth.tar

the web page is not responding. Kindly help me in resolving this issue.

**Comment by danieljf24** [comment]
Fixed. The trained checkpoints can also be downloaded from Baidu pan ([URL](https://pan.baidu.com/s/1lg23K93lVwgdYs5qnTuMFg), password:p3p0).

**Comment by danieljf24** [comment]
Please use the new url.
wget -P $MODELDIR http://8.210.46.84:8787/tpami2021/checkpoints/msrvtt10k_model_best.pth.tar
